"""Pydantic models for consultation-requests skill."""

from enum import StrEnum

from pydantic import BaseModel, Field


class ConsultationStatus(StrEnum):
    """Consultation request status."""

    pending = "pending"
    received = "received"
    integrated = "integrated"
    rejected = "rejected"


class VetInfo(BaseModel):
    """Veterinarian info (reference vet)."""

    nom: str = Field(..., description="Nom du vétérinaire")
    prenom: str = Field(..., description="Prénom du vétérinaire")
    clinique: str = Field(..., description="Clinique/cabinet")
    email: str = Field(..., description="Email professionnel")
    telephone: str = Field(..., description="Téléphone")
    adresse: str | None = Field(None, description="Adresse")


class OwnerInfo(BaseModel):
    """Owner/propriétaire info."""

    nom: str = Field(..., description="Nom du propriétaire")
    prenom: str = Field(..., description="Prénom du propriétaire")
    email: str | None = Field(None, description="Email")
    telephone: str | None = Field(None, description="Téléphone")


class AnimalInfo(BaseModel):
    """Animal (patient) info."""

    nom: str = Field(..., description="Nom de l'animal")
    espece: str = Field(..., description="Espèce (Chien, Chat, Lapin, NAC, etc.)")
    race: str | None = Field(None, description="Race")
    sexe: str | None = Field(None, description="Sexe (M, F, Castré, Stérilisé)")
    date_naissance: str | None = Field(None, description="Date de naissance (YYYY-MM-DD)")
    puce: str | None = Field(None, description="Numéro de puce")
    poids: float | None = Field(None, description="Poids en kg")


class ConsultationRequest(BaseModel):
    """Consultation request from WordPress."""

    uuid: str = Field(..., description="Unique identifier (generated by WP)")
    submitter_type: str = Field(..., description="Type: 'vet' ou 'owner'")
    vet: VetInfo | None = Field(None, description="Référant vet info (if vet)")
    owner: OwnerInfo | None = Field(None, description="Propriétaire info (optional if vet submitter)")
    animal: AnimalInfo = Field(..., description="Patient info")
    motif: str = Field(..., description="Motif de la demande")
    specialite: str = Field(
        ...,
        description="Spécialité souhaitée (imagerie, chirurgie, locomoteur)",
    )
    urgence: bool = Field(False, description="Est-ce une demande urgente?")
    traitements_en_cours: str | None = Field(None, description="Traitements actuels")
    fichiers: list[str] = Field(default_factory=list, description="URLs des fichiers uploadés")


class ConsultationResponse(BaseModel):
    """Response for a consultation request."""

    id: int = Field(..., description="Database ID")
    uuid: str = Field(..., description="Unique identifier")
    status: ConsultationStatus = Field(..., description="Current status")
    submitted_at: str = Field(..., description="Submission datetime (ISO)")
    submitter_type: str
    data: ConsultationRequest = Field(..., description="Full request data")
    files_local: list[str] | None = Field(None, description="Local file paths")
    erp_client_id: int | None = Field(None, description="VetoPartner client ID")
    erp_animal_id: int | None = Field(None, description="VetoPartner animal ID")
    erp_consult_id: int | None = Field(None, description="VetoPartner consultation ID")
    integrated_at: str | None = Field(None, description="Integration datetime")


class ScorimmоLeadInput(BaseModel):
    """Scorimmo lead input for from-scorimmo endpoint."""

    lead_id: int = Field(..., description="Scorimmo lead ID")
    customer_first_name: str = Field("", description="Prospect first name")
    customer_last_name: str = Field("", description="Prospect last name")
    customer_email: str | None = Field(None, description="Prospect email")
    customer_phone: str | None = Field(None, description="Prospect phone")
    animal_nom: str | None = Field(None, description="Animal name")
    animal_race: str | None = Field(None, description="Animal race")
    veto_habituel: str | None = Field(None, description="Usual veterinarian")
    motif: str | None = Field(None, description="Consultation reason")
    origin: str | None = Field(None, description="Lead origin")
    created_at: str | None = Field(None, description="Creation datetime")


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = "ok"
    service: str = ""
    version: str = ""
    timestamp: str = ""
